### ISSUE TITLE
consistency issue

### ISSUE THREAD

**Issue by Visual-Studio-Coder** [EvanZhouDev/cronix#3]
The text that says "CRONIX" in the top left corner does not highlight/underline when the cursor hovers over it, unlike the rest of the tab bar items. Make it highlight white or underline white so that it looks like a button that is supposed to be clicked. This improves consistency.
![Screenshot 2023-05-07 at 9 42 51 PM](https://user-images.githubusercontent.com/78756662/236735582-75f29372-9643-49d1-a9a3-e53475ae295a.png)

**Comment by EvanZhouDev** [comment]
Fixed in b802dff0cfd2fb354a4061081df263bbdb5c14b3.

**Comment by Visual-Studio-Coder** [comment]
I think that the color the CRONIX text highlights to is brighter than when you hover over some other icon. Also there is a longer animation for the CRONIX text to fully glow compared to the other icons.
<img width="65" alt="image" src="https://github.com/EvanZhouDev/cronix/assets/78756662/a33cccce-3f26-4e2a-bd49-a4e283ae9fc2">
<img width="145" alt="image" src="https://github.com/EvanZhouDev/cronix/assets/78756662/ae0af0c7-5a9a-4b52-ac6c-3afbab21eae3">

**Comment by EvanZhouDev** [comment]
It wasn't meant to be a button in the first place. It was supposed to be a logo. I think perhaps we are better off without any form of a hover animation at all. See [Monkeytype's logo](https://monkeytype.com/). If you agree, I will revert the changes.
